version: "3.3"

services:
  #Node 1
  re1:
    image: redislabs/redis:latest
    container_name: re1
    restart: unless-stopped
    tty: true
    cap_add: 
      - ALL
    ports:
      - "18443:8443"
      - "12000:12000"
    volumes:
      - ./:/home
    dns: 172.22.0.20
    networks:
      re_cluster:
        ipv4_address: 172.22.0.11

  #Node 2
  re2:
    image: redislabs/redis:latest
    container_name: re2
    restart: unless-stopped
    tty: true
    cap_add: 
      - ALL
    ports:
      - "28443:8443"
    volumes:
      - ./:/home
    dns: 172.22.0.20
    networks:
      re_cluster:
        ipv4_address: 172.22.0.12

  #Node 3
  re3:
    image: redislabs/redis:latest
    container_name: re3
    restart: unless-stopped
    tty: true
    cap_add: 
      - ALL 
    ports:
      - "38443:8443"
    volumes:
      - ./:/home
    dns: 172.22.0.20
    networks:
      re_cluster:
        ipv4_address: 172.22.0.13

  #dns for the docker network
  bind:
    image: sameersbn/bind
    volumes:
      - ./dns-configs/bind-cluster:/data
    container_name: bind
    ports:
      - 10000:10000
    dns: 172.22.0.20
    networks:
      re_cluster:
        ipv4_address: 172.22.0.20

#Docker Networks
networks:
  re_cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
