AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Deploy Redis Instances in a region

Mappings:

  RegionMap:
    us-east-1: # Virginia
      "REDISEC2AMI" : "ami-0d894ea5521c64557"
      "EC2AMI" : "ami-08e4e35cccc6189f4"
    us-east-2: # Ohio
      "REDISEC2AMI" : "ami-082a25bc38620fc4d"
      "EC2AMI" : "ami-001089eb624938d9f"
    us-east-3: # NCALIF
      "REDISEC2AMI" : "ami-01773f954c3875420"
      "EC2AMI" : "ami-02d03ce209db75523"
    us-west-2: # Oregon
      "REDISEC2AMI" : "ami-05037ab6f618ed336"
      "EC2AMI" : "ami-066333d9c572b0680"
    ap-south-1: # Mumbai
      "REDISEC2AMI" : "ami-0eefc21aa52001198"
      "EC2AMI" : "ami-0af25d0df86db00c1"
    ap-northeast-2: # Seoul
      "REDISEC2AMI" : "ami-0967b7ff9a7ba331e"
      "EC2AMI" : "ami-0b1d3b1941f23c7d5"
    ap-southeast-1: # Singapore
      "REDISEC2AMI" : "ami-052d3e5a59fc4a877"
      "EC2AMI" : "ami-0356b1cd4aa0ee970"
    ap-southeast-2: # Sydney 
      "REDISEC2AMI" : "ami-097cbef0451a30da5"
      "EC2AMI" : "ami-01dc883c13e87eeda"
    ap-northeast-1: # Tokyo
      "REDISEC2AMI" : "ami-0ce04ab8bcd5de2e9"
      "EC2AMI" : "ami-032d6db78f84e8bf5"
    eu-central-1: # Frankfurt
      "REDISEC2AMI" : "ami-09304ee2fe70b3aad"
      "EC2AMI" : "ami-05cafdf7c9f772ad2"
    eu-west-1: # Ireland
      "REDISEC2AMI" : "ami-03b7776ede7f47475"
      "EC2AMI" : "ami-01efa4023f0f3a042"
    eu-west-2: # London
      "REDISEC2AMI" : "ami-0c2b997e5c91153e0"
      "EC2AMI" : "ami-0fdbd8587b1cf431e"
    eu-west-3: # Paris  
      "REDISEC2AMI" : "ami-0176733f200a89b17"
      "EC2AMI" : "ami-031eb8d942193d84f"
    eu-north-1: # Stockholm 
      "REDISEC2AMI" : "ami-040e6fa2d290e7b9b"
      "EC2AMI" : "ami-067a92fcca2611950"
    sa-east-1: # Sao Paulo 
      "REDISEC2AMI" : "ami-06d197a564493b29b"
      "EC2AMI" : "ami-06078a297452ba5aa"

Parameters:
  RedisDatabasePort: 
    Description: Specify database port used for Redis
    Type: String
  ClusterName: 
    Description: Prefix Name of the Redis Cluster
    Type: String
  HostedZoneName: 
    Description: Hosted Zone Name to use.  This with the prefix cluster name is redis cluster name
    Type: String
  HostedZoneId:
    Description: HostedZoneNames can be duplicate so use Zone Id
    Type: String
  ClusterUserName:
    Description: cluster username email address
    Type: String
  ClusterPassword:
    Description: cluster password
    Type: String
  ClusterURL:
    Description: cluster URL
    Type: String
  LocalIp:
    Description: local IP address used for security group ssh port opening
    Type: String
  S3Bucket:
    Description: S3Bucket for holding redis connector spillage
    Type: String
  KeyPair:
    Description: key pair name for ec2 instances
    Type: String
  NumberInstances:
    Description: Number of Redis EC2 instances for this region
    Type: Number
    MinValue: 1
    MaxValue: 3
    Default: 3
  RedisEC2InstType:
    Description: Amazon EC2 Instance Type  m4 and m5.xlarge 4-16 m5 has better network, 2xlarge 8-13,  r4.xlarge 4 30.5, 8 61
    Type: String
    Default: r4.2xlarge
    AllowedValues:
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - c5a.xlarge
      - c5a.2xlarge
      - c5a.4xlarge
      - c5a.8xlarge
      - c5a.16xlarge
      - i3.large
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - i3.16xlarge
    ConstraintDescription: Must be a valid EC2 instance type.

  EC2InstType:
    Description: Amazon EC2 Instance Type for app node 
    Type: String
    Default: i3.2xlarge
    AllowedValues:
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - c5a.large
      - c5a.xlarge
      - c5a.2xlarge
      - c5a.4xlarge
      - c5a.8xlarge
      - c5a.16xlarge
      - i3.large
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.8xlarge
      - i3.16xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
  VpcCIDR:
    Description: Enter the VPC CIDR range in the form x.x.x.x/16.
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/16.
    Default: 10.20.0.0/16
  UseRedisElasticIP:
    Description: Flag to fixed IPs for the redis nodes
    Type: String
    Default: false
    AllowedValues:
      - true
      - false


Conditions:
  Create-One: !Equals [ !Ref NumberInstances, 1 ]
  Create-Two: !Equals [ !Ref NumberInstances, 2 ]
  Create-Three: !Equals [ !Ref NumberInstances, 3 ]
  Do-Two: !Or
    - !Condition Create-Two
    - !Condition Create-Three
  Create-ElasticIps: !Equals [ !Ref UseRedisElasticIP, true ]
  No-ElasticIps: !Equals [ !Ref UseRedisElasticIP, false ]
  Do-Two-Elastic: !And
    - !Condition Do-Two
    - !Condition Create-ElasticIps
  Do-Two-No-Elastic: !And
    - !Condition Do-Two
    - !Condition No-ElasticIps
  Do-Three-Elastic: !And
    - !Condition Create-Three
    - !Condition Create-ElasticIps
  Do-Three-No-Elastic: !And
    - !Condition Create-Three
    - !Condition No-ElasticIps
  

Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: VPCStack.yaml
      TimeoutInMinutes: 10
      Parameters:
        LocalIp:
          Ref: LocalIp
        VpcCIDR:
          Ref: VpcCIDR
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7aa57bac-380e-4523-a72b-ef898d0a0367

  IPAddressVM1:
    Type: AWS::EC2::EIP
    Condition: Create-ElasticIps

  IPAssocVM1:
    Type: AWS::EC2::EIPAssociation
    Condition: Create-ElasticIps
    Properties:
      InstanceId: !Ref RedisEC2VM1
      EIP: !Ref IPAddressVM1

  RedisEC2VM1:
    Type:  AWS::EC2::Instance
    DependsOn: 
      - VPCStack
    Properties:
      ImageId: 
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - REDISEC2AMI
      InstanceType: !Ref RedisEC2InstType
      SubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1Id
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !GetAtt VPCStack.Outputs.WorkshopSecurityGroup
      Tags:
        - Key: 'Name'
          Value: !Join ['',  [!Ref AWS::StackName, 'VM1'] ]
      UserData:
        Fn::Base64:
          !Sub |
             #!/bin/bash -xe
             sudo  bash -l
             yum -y install git wget bind-utils
             /opt/redislabs/bin/rladmin cluster create name ${RedisNSRecord} persistent_path /var/opt/redislabs/persist  ephemeral_path /var/opt/redislabs/tmp  addr $(hostname -i) username ${ClusterUserName} password ${ClusterPassword} external_addr $(dig +short myip.opendns.com @resolver1.opendns.com) register_dns_suffix
             cd /home/ec2-user
             mkdir rlec
             cd rlec
             wget https://s3.amazonaws.com/redis-enterprise-software-downloads/6.2.8/redislabs-6.2.8-53-rhel7-x86_64.tar
             tar xvf redislabs-6.2.8-53-rhel7-x86_64.tar
             ./install.sh -y --allow-same-version

  IPAddressVM2:
    Condition: Do-Two-Elastic
    Type: AWS::EC2::EIP

  IPAssocVM2:
    Condition: Do-Two-Elastic
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref RedisEC2VM2
      EIP: !Ref IPAddressVM2

  RedisEC2VM2:
    Type:  AWS::EC2::Instance
    Condition: Do-Two
    DependsOn: 
      - VPCStack
      - RedisEC2VM1
    Properties:
      ImageId: 
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - REDISEC2AMI
      InstanceType: !Ref RedisEC2InstType
      SubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1Id
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !GetAtt VPCStack.Outputs.WorkshopSecurityGroup
      Tags:
        - Key: 'Name'
          Value: !Join ['',  [!Ref AWS::StackName, 'VM2'] ]
      UserData:
        Fn::Base64:
          !Sub |
              #!/bin/bash -xe
              sudo  bash -l
              yum -y install bind-utils git wget
              cd /home/ec2-user
              mkdir rlec
              cd rlec
              wget https://s3.amazonaws.com/redis-enterprise-software-downloads/6.2.8/redislabs-6.2.8-53-rhel7-x86_64.tar
              tar xvf redislabs-6.2.8-53-rhel7-x86_64.tar
              /opt/redislabs/bin/rl_uninstall.sh
              ./install.sh -y --allow-same-version
              sudo  bash -l
              /opt/redislabs/bin/rladmin cluster join nodes ${RedisEC2VM1.PrivateIp} persistent_path /var/opt/redislabs/persist  ephemeral_path /var/opt/redislabs/tmp  addr $(hostname -i) username ${ClusterUserName} password ${ClusterPassword} external_addr $(dig +short myip.opendns.com @resolver1.opendns.com)

  IPAddressVM3:
    Condition: Do-Three-Elastic
    Type: AWS::EC2::EIP

  IPAssocVM3:
    Condition: Do-Three-Elastic
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref RedisEC2VM3
      EIP: !Ref IPAddressVM3

  RedisEC2VM3:
    Condition: Create-Three
    Type:  AWS::EC2::Instance
    DependsOn: 
      - VPCStack
      - RedisEC2VM1
    Properties:
      ImageId: 
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - REDISEC2AMI
      InstanceType: !Ref RedisEC2InstType
      SubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1Id
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !GetAtt VPCStack.Outputs.WorkshopSecurityGroup
      Tags:
        - Key: 'Name'
          Value: !Join ['',  [!Ref AWS::StackName, 'VM3'] ]
      UserData:
        Fn::Base64:
          !Sub |
              #!/bin/bash -xe
              sudo  bash -l
              yum -y install bind-utils git wget
              cd /home/ec2-user
              mkdir rlec
              cd rlec
              wget https://s3.amazonaws.com/redis-enterprise-software-downloads/6.2.8/redislabs-6.2.8-53-rhel7-x86_64.tar
              tar xvf redislabs-6.2.8-53-rhel7-x86_64.tar
              /opt/redislabs/bin/rl_uninstall.sh
              ./install.sh -y --allow-same-version
              sudo  bash -l
              /opt/redislabs/bin/rladmin cluster join nodes ${RedisEC2VM1.PrivateIp} persistent_path /var/opt/redislabs/persist  ephemeral_path /var/opt/redislabs/tmp  addr $(hostname -i) username ${ClusterUserName} password ${ClusterPassword} external_addr $(dig +short myip.opendns.com @resolver1.opendns.com)

  AppEC2Instance:
    Type:  AWS::EC2::Instance
    DependsOn: 
      - VPCStack
    Properties:
      ImageId: 
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - EC2AMI
      InstanceType: !Ref EC2InstType
      SubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1Id
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !GetAtt VPCStack.Outputs.WorkshopSecurityGroup
      Tags:
        - Key: 'Name'
          Value: !Join ['',  [!Ref AWS::StackName, 'APPEC2'] ]
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          DeleteOnTermination: 'true'
          VolumeSize: '60'
          VolumeType: gp2
      UserData:
        Fn::Base64:
          !Sub |
             #!/bin/bash -xe
             sudo  bash -l
             yum -y install git wget bind-utils maven java-1.8.0-openjdk
             cd /home/ec2-user
             git clone https://github.com/jphaugla/redisSMSLuaA-A.git
             sudo chown -R ec2-user:ec2-user redisSMSLuaA-A
             git clone https://github.com/jphaugla/redisJSONProductCatalog.git
             sudo chown -R ec2-user:ec2-user redisJSONProductCatalog
             yum -y install autoconf automake make gcc-c++
             yum -y install pcre-devel zlib-devel libmemcached-devel libevent-devel openssl-devel
             git clone git://github.com/RedisLabs/memtier_benchmark.git
             cd memtier_benchmark
             autoreconf -ivf
             ./configure
             make
             make install
             cd /home/ec2-user
             chown -R ec2-user:ec2-user memtier_benchmark
             cp -f redisSMSLuaA-A/grafana.repo /etc/yum.repos.d
             cp -f redisSMSLuaA-A/prometheus.repo /etc/yum.repos.d
             yum -y makecache fast
             yum install -y grafana
             systemctl enable --now grafana-server.service
             yum install -y prometheus2.x86_64
             cp -f redisSMSLuaA-A/prometheus.yml /etc/prometheus
             echo "      - targets: [${RedisNSRecord}:8070]">> /etc/prometheus/prometheus.yml
             systemctl enable --now prometheus.service
             grafana-cli plugins install redis-datasource
             systemctl restart grafana-server
             

  RedisARecord1E:
    Type: AWS::Route53::RecordSet
    Condition: Create-ElasticIps
    DependsOn: 
      - IPAddressVM1
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: DNS name for my instance
      Name: !Join ['',  ['node1.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  
      Type: A
      TTL: 900
      ResourceRecords:
        - !Ref IPAddressVM1

  RedisARecord1N:
    Type: AWS::Route53::RecordSet
    Condition: No-ElasticIps
    DependsOn: 
      - RedisEC2VM1
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: DNS name for my instance
      Name: !Join ['',  ['node1.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  
      Type: A
      TTL: 900
      ResourceRecords:
        - !GetAtt RedisEC2VM1.PublicIp

  RedisARecord2E:
    Condition: Do-Two-Elastic
    Type: AWS::Route53::RecordSet
    DependsOn: 
      - IPAddressVM2
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: DNS name for my instance
      Name: !Join ['',  ['node2.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  
      Type: A
      TTL: 900
      ResourceRecords:
        - !Ref IPAddressVM2

  RedisARecord2N:
    Condition: Do-Two-No-Elastic
    Type: AWS::Route53::RecordSet
    DependsOn: 
      - RedisEC2VM2
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: DNS name for my instance
      Name: !Join ['',  ['node2.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  
      Type: A
      TTL: 900
      ResourceRecords:
        - !GetAtt RedisEC2VM1.PublicIp

  RedisARecord3E:
    Condition: Do-Three-Elastic
    Type: AWS::Route53::RecordSet
    DependsOn: 
      - IPAddressVM3
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: DNS name for my instance
      Name: !Join ['',  ['node3.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  
      Type: A
      TTL: 900
      ResourceRecords:
        - !Ref IPAddressVM3

  RedisARecord3N:
    Condition: Do-Three-No-Elastic
    Type: AWS::Route53::RecordSet
    DependsOn: 
      - RedisEC2VM3
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: DNS name for my instance
      Name: !Join ['',  ['node3.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  
      Type: A
      TTL: 900
      ResourceRecords:
        - !GetAtt RedisEC2VM3.PublicIp

  RedisNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Join ['', [ !Ref ClusterName, ., !Ref HostedZoneName ] ]
      Type: NS
      TTL: '900'
      ResourceRecords:
        - !Join ['', [ 'node1.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  
        - !Join ['', [ 'node2.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  
        - !Join ['', [ 'node3.', !Ref ClusterName, ., !Ref HostedZoneName ] ]  

Outputs:

  Subnets:
    Description: Subnets for workshop
    Value: !Join [',', [!GetAtt VPCStack.Outputs.PublicSubnet1Id]]  

  WorkshopSecurityGroup:
    Description: 'Security Group'
    Value: !GetAtt VPCStack.Outputs.WorkshopSecurityGroup

  RedisInstancePrivateDNS:
    Description: 'Private DNS for Redis EC2 instance'
    Value: !GetAtt RedisEC2VM1.PrivateDnsName

  RedisInstancePublicDNS:
    Description: 'Public DNS for Redis EC2 instance'
    Value: !GetAtt RedisEC2VM1.PublicDnsName

  RedisInstancePrivateIP:
    Description: 'Private IP for Redis EC2 instance'
    Value: !GetAtt RedisEC2VM1.PrivateIp

  RedisInstancePublicIP:
    Description: 'Public IP for Redis EC2 instance'
    Value: !GetAtt RedisEC2VM1.PublicIp

  RedisNSRecord:
    Description: 'The NS Record Name for Redis'
    Value: !Ref RedisNSRecord

  RedisPort:
    Description: 'The Port used for Redis Database'
    Value: !Ref RedisDatabasePort
