Transform: AWS::Serverless-2016-10-31
Parameters:
  AthenaCatalogName:
    Description: The name you will give to this catalog in Athena. It will also be used as the function name. This name must satisfy the pattern ^[a-z0-9-_]{1,64}$
    Type: String
    AllowedPattern: ^[a-z0-9-_]{1,64}$
  SpillBucket:
    Description: The name of the bucket where this function can spill data.
    Type: String
  SpillPrefix:
    Description: The prefix within SpillBucket where this function can spill data.
    Type: String
    Default: athena-spill
  LambdaTimeout:
    Description: Maximum Lambda invocation runtime in seconds. (min 1 - 900 max)
    Default: 900
    Type: Number
  LambdaMemory:
    Description: Lambda memory in MB (min 128 - 3008 max).
    Default: 3008
    Type: Number
  DisableSpillEncryption:
    Description: 'WARNING: If set to ''true'' encryption for spilled data is disabled.'
    Default: 'false'
    Type: String
  SecurityGroupIds:
    Description: One or more SecurityGroup IDs corresponding to the SecurityGroup that should be applied to the Lambda function. (e.g. sg1,sg2,sg3)
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIds:
    Description: One or more Subnet IDs corresponding to the Subnet that the Lambda function can use to access you data source. (e.g. subnet1,subnet2)
    Type: List<AWS::EC2::Subnet::Id>
  SecretNameOrPrefix:
    Description: The name or prefix of a set of names within Secrets Manager that this function should have access to. (e.g. redis-*).
    Type: String
Resources:
  ConnectorConfig:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          disable_spill_encryption:
            Ref: DisableSpillEncryption
          spill_bucket:
            Ref: SpillBucket
          spill_prefix:
            Ref: SpillPrefix
      FunctionName:
        Ref: AthenaCatalogName
      Handler: com.amazonaws.athena.connectors.redis.RedisCompositeHandler
      CodeUri:
        Bucket: awsserverlessrepo-changesets-plntc6bfnfj
        Key: 735486936198/arn:aws:serverlessrepo:us-east-1:292517598671:applications-AthenaRedisConnector-versions-2021.37.1/e2f8cc5d-6db3-4644-9a49-8a5ab905315b
      Description: Enables Amazon Athena to communicate with Redis, making your Redis data accessible via SQL
      Runtime: java8
      Timeout:
        Ref: LambdaTimeout
      MemorySize:
        Ref: LambdaMemory
      Policies:
      - Statement:
        - Action:
          - secretsmanager:GetSecretValue
          Effect: Allow
          Resource:
            Fn::Sub: arn:${AWS::Partition}:secretsmanager:*:*:secret:${SecretNameOrPrefix}
        Version: '2012-10-17'
      - Statement:
        - Action:
          - glue:GetTableVersions
          - glue:GetPartitions
          - glue:GetTables
          - glue:GetTableVersion
          - glue:GetDatabases
          - glue:GetTable
          - glue:GetPartition
          - glue:GetDatabase
          - athena:GetQueryExecution
          - s3:ListAllMyBuckets
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      - S3CrudPolicy:
          BucketName:
            Ref: SpillBucket
      - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          Ref: SecurityGroupIds
        SubnetIds:
          Ref: SubnetIds
